#!/bin/bash

setDrive() {
	uuid=$(diskutil info "$volume" | grep UUID | cut -d ':' -f2 | tr -d ' ')
	volumeName=$(diskutil info "$volume" | grep "Volume Name" | cut -d ':' -f2 | tr -d ' ')
	if [ "$uuid" = "" ]; then
		drive="LABEL=${volumeName// /\\040} none ntfs rw,auto,nobrowse #${volumeName// /}"
	else
		drive="UUID=$uuid none ntfs rw,auto,nobrowse #${volumeName// /}"
	fi
}

setupDrive() {
	echo $drive >> /etc/fstab
	device=$(diskutil info "$volume" | grep "Device Node" | cut -d ':' -f2 | tr -d ' ')
	diskutil unmount "$volume"
	diskutil mount $device
}

manualAdd() {
	setDrive
	while read fileLine; do
		if [ "$drive" = "$fileLine" ]; then
			echo "$volume already configured."
			exit 0;
		fi
	done < /etc/fstab
	setupDrive
	open "$volume"
}

autoAdd() {
	setDrive
	while read fileLine; do
		if [ "$drive" = "$fileLine" ]; then
			echo "$volume already configured."
			return 1;
		fi
	done < /etc/fstab
	if [ "$?" -ne 1 ]; then
		echo "New Drive $volume is added."
		echo $drive >> /etc/fstab
		device=$(diskutil info "$volume" | grep "Device Node" | cut -d ':' -f2 | tr -d ' ')
		diskutil unmount "$volume"
		diskutil mount $device
	fi
}

checkDrive() {
	filetype=$(diskutil info "$volume" | grep "Type (Bundle):" | cut -d ':' -f2 | tr -d ' ')
	if [ "$filetype" = "ntfs" ]; then
		if [ "$1" = "auto" ]; then
			autoAdd
		else
			manualAdd
		fi
	fi
}

addDriveAuto() {
	for volume in "/Volumes"/*
	do
		checkDrive auto
	done
}

addDrive() {
	select volume in "/Volumes"/*
	do
		case "$volume" in
			"$QUIT")
				echo "Exiting..."
				break
				;;
			*)
				echo "You picked "$volume" "
				checkDrive
				;;
		esac
	done
}

listDrive() {
	while read fileLine; do
		dname=($(echo "$fileLine" | awk '{print $NF}'))
		drives+=(${dname//#/})
	done < /etc/fstab
	select drive in ${drives[@]}
	do
		case "$drive" in
			"$QUIT")
				echo "Exiting."
				break
				;;
			*)
				echo "You picked "$drive" to remove"
				break
				;;
		esac
	done
}

removeDrive() {
	listDrive
	sed -i.bak "/$drive/d" /etc/fstab
	rm /etc/fstab.bak
}

usage() {
	echo "Usage : $0 [-h|--help|help] [-a|add] [-r|remove]"
	echo "-h | --help | help : Help. Display this message and quit."
	echo "-a | add           : Add new NTFS Drives to fstab."
	echo "-r | remove        : Remove NTFS Drives from fstab."
	exit
}

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
	echo "This script need to run as ROOT. Try sudo."
else
	if [ -z $1 ]; then
		addDriveAuto
	else
		case $1 in
			-a|add)
				addDrive
				;;
			-r|remove)
				removeDrive
				;;
			-h|--help|help)
				usage
				;;
			*)
				usage
				;;
		esac
	fi
fi
